#!/usr/bin/env bash
#script that displays the content of
#the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username _ gid _ home _ uid _  _ password _;
do
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$username" "$gid" "$home" "$home" "$uid" "$password" "$username"
done < "/etc/passwd"
