#!/usr/bin/env bash
#Program that display the time in hours and minutes

Hours=0
while [ $Hours -lt 12 ];
do
echo "Hour $Hours"

min=1
while [ $min -lt 59 ];
do
	echo $min
((min++))
done
((Hours++))
done
