#!/usr/bin/env bash
#a Bash script that gives you information about the school file.

var="school"
if [[ -e $var ]];
then
	echo "$var file exists"
	if [[ ! -s $var ]];
	then
		echo "$var file is empty"
	elif [[ -s $var ]];
	then
		echo "$var file is not empty"
	else
		echo "$var is a regular file"
	fi
else
	echo "$var file does not exist"
fi
