#!/usr/bin/env bash
#  Bash script that configures an Ubuntu server with the below requirements.
#  Requirements:
#  localhost resolves to 127.0.0.2localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8.

host_name="/etc/hosts"
local_host_ip="127.0.0.2"
facebook_ip="8.8.8.8"

echo "localhost $local_host_ip" >> $host_name
echo "facebook.com $facebook_ip" >> $host_name
