#!/usr/bin/env bash
#  Bash script that configures an Ubuntu server with the below requirements.
#  Requirements:
#  localhost resolves to 127.0.0.2localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8.


local_host_ip="127.0.0.2"
facebook_ip="8.8.8.8"

sudo cp /etc/hosts /hosts.new
sudo sed -i "/localhost/ s/.*/localhost $local_host_ip/" "/hosts.new"
sudo sed -i "/facebook.com/ s/.*/facebook.com $facebook_ip/" "/hosts.new"
sudo cp -f /hosts.new /etc/hosts
